### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [arizvisa/Ax#1]
this looks interesting, but any README soon?

cheers.

**Comment by arizvisa** [comment]
Hah! That was quick..

**Comment by arizvisa** [comment]
Lol, nah. This isn't really a legitimate tool that I plan on srsly maintaining. A friend and I just needed an ActiveX control to simulate some things for part of some project. Turned out that we needed a disassembler too.

I guess if this ever evolves to a point where it becomes release-worthy, I could add a README and documentation and things, but this was initially intended to be throwaway code. ;)

**Comment by arizvisa** [comment]
Ok. Added a really minimalistic Readme. ;-)
